import { notoSansKR, archivo } from './fonts'

import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko" className={`${notoSansKR.variable} ${archivo.variable}`}>
      <body>{children}</body>
    </html>
  )
}
